---
title: "Blast_Viz"
author: "Liam McFall"
date: "1/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}

source("/Users/liammcfall/CanisiusBaseball/BlastMergingCleaning.R")
library(dplyr)
library(ggplot2)
library(tidyr)
library(magrittr)
library(ggalt)
library(tibble)
library(gridExtra)

```
Load data
 - testing by loading 1 player for month of january
 
```{r}

burlingame <- aggregateBlast('/Users/liammcfall/CanisiusBaseball/BlastData/BlastPlayers/Burlingame/')
burlingame <- blastClean(burlingame)
burlingame$week <- as.factor(isoweek(burlingame$Date))

```

Subset last 2 weeks of data for the player using iso standard week formatting. M-S

ie. Week 1 of 2020 was 12/30/19 - 01/05/20

Week 3 - 01/13/20 - 01/19/20

Week 4 - 01/20/20 - 01/26/20

```{r}

burlingameSub <- subset(burlingame, week %in% c(3, 4))

```

Metrics tables

```{r}

burlingameGrouped <- burlingameSub %>%
  group_by(week) %>%
  summarise("Rotational Acceleration (g)" = mean(Rotational.Acceleration..g.), 
            "On-Plane Efficiency (%)" = mean(On.Plane.Efficiency....), 
            "Connection Impact (deg)" = mean(Connection.at.Impact..deg.), 
            "Early Connection (deg)" = mean(Early.Connection..deg.),
            "Commit Time (s)" = mean(Time.to.Contact..sec.),
            "Bat Speed" = mean(Bat.Speed..mph.),
            "Attack Angle (deg)" = mean(Attack.Angle..deg.)) %>%
  t() %>%
  as.data.frame()

colnames(burlingameGrouped) <- c(paste("Week", burlingameGrouped[1,1]), paste("Week", burlingameGrouped[1,2]))
burlingameGrouped <- burlingameGrouped[-1,]
burlingameGrouped[,1] <- as.numeric(as.character(burlingameGrouped[,1]))
burlingameGrouped[,2] <- as.numeric(as.character(burlingameGrouped[,2]))
burlingameGrouped$Difference <- (burlingameGrouped[,2] - burlingameGrouped[,1])

burlingameSwingCount <- burlingameSub %>%
  group_by(week) %>%
  tally(name = "# Swings")

```

Experimentation with charts from the pdf posted in slack

```{r rotVope}

rotVope <- ggplot(burlingameSub, aes(x = On.Plane.Efficiency...., y = Rotational.Acceleration..g.)) +
  geom_encircle(aes(fill = week), alpha = .5, expand = .01) +
  geom_point(aes(color = week)) +
  labs(y = 'Rotational Acceleration (g)', x = 'On Plane Efficieny (%)')


```

```{r attackVspeed}

attackVspeed <- ggplot(burlingameSub, aes(x = Bat.Speed..mph., y = Attack.Angle..deg.)) +
  geom_encircle(aes(fill = week), alpha = .5, expand = .01) +
  geom_point(aes(color = week)) +
  labs(y = 'Attack Angle (deg)', x = 'Bat Speed (mph)')

```

```{r rotVcommit}

rotVcommit <- ggplot(burlingameSub, aes(x = (Time.to.Contact..sec. * 1000), y = Rotational.Acceleration..g.)) +
  geom_encircle(aes(fill = week), alpha = .5, expand = .01) +
  geom_point(aes(color = week)) +
  labs(y = 'Rotational Acceleration (g)', x = 'Time to Contact (ms)')

```

```{r conVvert}

conVvert <- ggplot(burlingameSub, aes(x = Vertical.Bat.Angle..deg., y = Connection.at.Impact..deg.)) +
  geom_encircle(aes(fill = week), alpha = .5, expand = .01) +
  geom_point(aes(color = week)) +
  labs(y = 'Connection at Impact (deg)', x = 'Vertical Bat Angle (deg)') +
  scale_x_reverse()

```

```{r earlyconVvert}

earlyconVvert <- ggplot(burlingameSub, aes(x = Vertical.Bat.Angle..deg., y = Early.Connection..deg.)) +
  geom_encircle(aes(fill = week), alpha = .5, expand = .01) +
  geom_point(aes(color = week)) +
  labs(y = 'Early Connection (deg)', x = 'Vertical Bat Angle (deg)') +
  scale_x_reverse()

```

```{r}

print(burlingameSwingCount)
print(burlingameGrouped)
grid.arrange(attackVspeed, rotVope, rotVcommit, conVvert, earlyconVvert, nrow = 3)

```

